MainWidget:

<MainWidget>:
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height
        padding: 50
        spacing: 20
        Label:
            id: my_label
            text:'TOOL-GO Inc.'
            font_size:32
        
        Button:
            text:'ScreenRecord'
            font_size: 32
            size_hint: .29,.11
            pos_hint: {'center_x':0.5}

            on_press: root.ScreenRecord()
            